#!/usr/bin/env python
'''
This is related to atatstatus.py, but has a simpler output.

it walks the atat directory print the status of each directory. For example:

./28                            -22.2079 eV/atom
./28/eos-exp/f-15               -21.4689 eV/atom
./28/eos-exp/f-12               -21.7704 eV/atom
./28/eos-exp/f-10               -21.9208 eV/atom
'''

import commands, glob, os

for dirpath,dirnames,filenames in os.walk('.'):

    if 'str.out' not in filenames:
        # not an atat directory
        continue

    if 'energy' in filenames:
        f = open(os.path.join(dirpath,'energy'))
        e = float(f.readline())
        f.close()

        print '%s\t% 1.4f eV/atom' % (dirpath.ljust(30),e)

    if 'error' in filenames:
        print '%s\t\terror' % (dirpath.ljust(30))

    if 'running' in filenames:
        jobids = glob.glob(dirpath + '/*.jobid')
        if len(jobids) > 0:
            f = open(jobids[0])
            jobid = f.readline()

            status,output = commands.getstatusoutput('qstat -f %s' % jobid)

            if 'qstat: Unknown Job Id' in output:
                jobstatus = 'Not in queue'
            else:
                jobstatus = ''

            print '%s\t\t\trunning\t%s\t%s' % (dirpath.ljust(30),jobid,jobstatus)
        else:
            print '%s\t\t\trunning\t%s' % (dirpath.ljust(30),'No jobid')
